<a href="https://colab.research.google.com/github/angiecombs11-ops/PurdueHW/blob/main/Deep_learning_ch_5_02_intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!pip install tensorflow==2.20.0 scikeras==0.13.0 keras==3.13.2


  Using cached tensorflow-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Using cached tensorflow-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (620.7 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-decision-forests 1.12.0 requires tensorflow==2.19.0, but you have tensorflow 2.20.0 which is incompatible.
tf-keras 2.19.0 requires tensorflow<2.20,>=2.19, but you have tensorflow 2.20.0 which is incompatible.
tensorflow-text 2.19.0 requires tensorflow<2.20,>=2.19.0, but you have tensorflow 2.20.0 which is incompatible.


In [15]:
# Disable oneDNN optimiations to avoid potientia minor numerical differences caused by floating-point round-off errors.
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

In [16]:
# Import TensorFlow and NumPy libraries
import tensorflow as tf
import numpy as np


In [17]:
# Create a rank 0 tensor (scalar) with a contstant vlaue of 4
rank_0_tensor = tf.constant(4)
# Print the rank 0 tensor
print(rank_0_tensor)


tf.Tensor(4, shape=(), dtype=int32)


In [18]:
# Create a rank 1 tensor (vector) with alues [2.0, 4.0, 5.0]
rank_1_tensor = tf.constant([2.0, 4.0, 5.0])
# Print the rank 1 tensor
print(rank_1_tensor)


tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


In [19]:
# Create a rank 2 tensor (matrix) with shape (3, 2) and specified values
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
# Print the rank 2 tensor
print(rank_2_tensor)


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [20]:
# Create a rank tensor flow with shape (3, 2, 5) and sequential values from 0 to 29
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])
    # Print the rank 3 tensor
print(rank_3_tensor)



tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [21]:
# Convert the rank 2 tensor to a NumPy array
rank_2_tensor.numpy()


array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [23]:
# Declare two 2x2 tensors a and b
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

# Perform element-wise addition
print(tf.add(a, b), "\n")
# Perfofm element-wise mulitplication
print(tf.multiply(a, b), "\n")
# Perfrom matrix multiplication
print(tf.matmul(a, b), "\n")


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [24]:
# Initialize a tensor c with specified values
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
# Calculate the maximum value in tensor c
print(tf.reduce_max(c))
# Find the index of teh maximum value in tensor c
print(tf.math.argmax(c))
# Apply the softmax function to tensor c
print(tf.nn.softmax(c))


tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [25]:
# Declare a 1x3 tensor x
x = tf.constant([1, 2, 3])

# Declare scalar and 1x3 tensor for braodcasting
y = tf.constant(2)
z = tf.constant([2, 2, 2])

# Perform element-wise mulitplication with scaler
print(tf.multiply(x, 2))
# Perform element-wise multiplication with another scaler
print(x * y)
# Perform element-wise multilication with another tensor
print(x * z)



tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [26]:
# Create a tensor x with shape (3, 1)
x = tf.constant([[1], [2], [3]])
# Print the shape of the tensor x
print(x.shape)



(3, 1)


In [27]:
reshaped = tf.reshape(x, [1,3])


In [28]:
# Print the shapes of the original and reshaped tensors
print(x.shape)
print(reshaped.shape)


(3, 1)
(1, 3)


In [29]:
# Create a ragged tensor with a variable number f elements along some axes
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)


<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [30]:
# Create a scaler string tensor
scalar_string_tensor = tf.constant("gray wolf")
# Print the scaler tensor
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)
